import React, { useCallback, useState } from 'react';
import { Sidebar, TopHeader } from '@/components/layout/shell';
import { AgentActivity } from '@/components/dashboard/agent-activity';
import { ChatWidget } from '@/components/dashboard/chat-widget';
import { AboutModal } from '@/components/dashboard/about-modal';
import { IssueCard } from '@/components/dashboard/issue-card';
import { Tabs, TabsList, TabsTrigger, TabsContent, Badge } from '@/components/ui';
import { MOCK_ISSUES, Issue } from '@/data/mock';

export default function Dashboard() {
  const [isRunning, setIsRunning] = useState(false);
  const [hasRunBefore, setHasRunBefore] = useState(true); // Seeded state
  const [issues, setIssues] = useState<Issue[]>(MOCK_ISSUES);
  
  // Reset data when re-running audit
  const handleRunAudit = () => {
    setIsRunning(true);
    setHasRunBefore(true);
    // When running, clear the board visually for effect, or show skeletons
    // For this demo, we'll just dim them or show an empty state until it finishes
  };

  const handleAuditComplete = useCallback(() => {
    setIsRunning(false);
    // Reset any dismissed actions to show the full board again for demo purposes
    setIssues(MOCK_ISSUES.map(issue => ({
      ...issue,
      actions: issue.actions.map(a => ({ ...a, status: 'pending' as const }))
    })));
  }, []);

  const handleActionApprove = (issueId: string, actionId: string) => {
    setIssues(prev => prev.map(issue => {
      if (issue.id === issueId) {
        return {
          ...issue,
          actions: issue.actions.map(action => 
            action.id === actionId ? { ...action, status: 'approved' } : action
          )
        };
      }
      return issue;
    }));
  };

  const handleActionDismiss = (issueId: string, actionId: string) => {
    setIssues(prev => prev.map(issue => {
      if (issue.id === issueId) {
        return {
          ...issue,
          actions: issue.actions.map(action => 
            action.id === actionId ? { ...action, status: 'dismissed' } : action
          )
        };
      }
      return issue;
    }));
  };

  const criticalIssues = issues.filter(i => i.severity === 'critical');
  const attentionIssues = issues.filter(i => i.severity === 'attention');
  const healthyIssues = issues.filter(i => i.severity === 'healthy');

  return (
    <div className="min-h-screen bg-background flex">
      <Sidebar />
      <div className="flex-1 md:pl-64 flex flex-col min-w-0">
        <TopHeader onRunAudit={handleRunAudit} isRunning={isRunning} />
        
        <main className="flex-1 p-4 md:p-8 overflow-y-auto">
          <div className="max-w-7xl mx-auto space-y-6">
            
            {/* Header Area */}
            <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 pb-2 border-b">
              <div>
                <h2 className="text-2xl font-bold tracking-tight text-foreground">Today's Operations Brief</h2>
                <p className="text-muted-foreground mt-1">Generated by SchoolOps AI based on overnight data sync.</p>
              </div>
              <div className="flex items-center gap-2">
                <AboutModal />
              </div>
            </div>

            {/* Main Layout Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              
              {/* Left Column (Issues) */}
              <div className="lg:col-span-2 space-y-6">
                <Tabs defaultValue="all" className="w-full">
                  <div className="flex items-center justify-between mb-4">
                    <TabsList className="bg-muted/50 p-1">
                      <TabsTrigger value="all" className="text-xs sm:text-sm">
                        All Items <Badge variant="secondary" className="ml-2 bg-background">{issues.length}</Badge>
                      </TabsTrigger>
                      <TabsTrigger value="critical" className="text-xs sm:text-sm data-[state=active]:text-destructive">
                        Critical <Badge variant="destructive" className="ml-2">{criticalIssues.length}</Badge>
                      </TabsTrigger>
                      <TabsTrigger value="attention" className="text-xs sm:text-sm data-[state=active]:text-warning">
                        Attention <Badge variant="warning" className="ml-2">{attentionIssues.length}</Badge>
                      </TabsTrigger>
                    </TabsList>
                  </div>

                  <div className={isRunning ? 'opacity-50 pointer-events-none transition-opacity duration-300 blur-[1px]' : 'transition-opacity duration-500'}>
                    <TabsContent value="all" className="space-y-4 m-0">
                      {issues.map(issue => (
                        <IssueCard 
                          key={issue.id} 
                          issue={issue} 
                          onActionApprove={handleActionApprove}
                          onActionDismiss={handleActionDismiss}
                        />
                      ))}
                    </TabsContent>
                    <TabsContent value="critical" className="space-y-4 m-0">
                      {criticalIssues.map(issue => (
                        <IssueCard 
                          key={issue.id} 
                          issue={issue} 
                          onActionApprove={handleActionApprove}
                          onActionDismiss={handleActionDismiss}
                        />
                      ))}
                      {criticalIssues.length === 0 && (
                        <div className="p-8 text-center border rounded-lg bg-card text-muted-foreground">No critical issues to display.</div>
                      )}
                    </TabsContent>
                    <TabsContent value="attention" className="space-y-4 m-0">
                      {attentionIssues.map(issue => (
                        <IssueCard 
                          key={issue.id} 
                          issue={issue} 
                          onActionApprove={handleActionApprove}
                          onActionDismiss={handleActionDismiss}
                        />
                      ))}
                      {attentionIssues.length === 0 && (
                        <div className="p-8 text-center border rounded-lg bg-card text-muted-foreground">No items need attention.</div>
                      )}
                    </TabsContent>
                  </div>
                </Tabs>
              </div>

              {/* Right Column (Agent Logs & Chat) */}
              <div className="space-y-6 flex flex-col h-full">
                <AgentActivity 
                  isRunning={isRunning} 
                  onComplete={handleAuditComplete} 
                  hasRunBefore={hasRunBefore} 
                />
                
                <div className="flex-1">
                  <ChatWidget />
                </div>
              </div>
              
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
